apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-server1
  namespace: default
spec:
  hosts:
    - mydevops.yao.net
  gateways:
    - istio-system/mydevops-istio-gateway
  exportTo:
    - "."
    - istio-system
  http:
    - match:
        - uri:
            prefix: /argocd123
      name: argocd-http
      route:
        - destination:
            host: argocd-server
            port:
              number: 443